const data = [
    {key: 'allchar', value: 'All Characters', text: 'All Characters'},
    {key: 'allbooks', value: 'All Books', text: 'All Books'},
    {key: 'allpla', value: 'All Planets', text: 'All Planets'},
    {key: 'allmagi', value: 'All Magic Systems', text: 'All Magic Systems'},
    {key: 'allsagas', value: 'All Sagas', text: 'All Sagas'},
    {key: 'kel', value: 'Kelsier', text: 'Kelsier'},
    {key: 'vin', value: 'Vin', text: 'Vin'},
    {key: 'saz', value: 'Sazed', text: 'Sazed'},
    {key: 'ras', value: 'Rashek', text: 'Rashek'},
    {key: 'kal', value: 'Kaladin', text: 'Kaladin'},
    {key: 'dal', value: 'Dalinar', text: 'Dalinar'},
    {key: 'esh', value: 'Eshonai', text: 'Eshonai'},
    {key: 'sha', value: 'Shallan', text: 'Shallan'},
    {key: 'vas', value: 'Vasher', text: 'Vasher'},
    {key: 'viv', value: 'Vivenna', text: 'Vivenna'},
    {key: 'sus', value: 'Susebron', text: 'Susebron'},
    {key: 'den', value: 'Denth', text: 'Denth'},
    {key: 'sca', value: 'Scadrial', text: 'Scadrial'},
    {key: 'ros', value: 'Roshar', text: 'Roshar'},
    {key: 'nal', value: 'Nalthis', text: 'Nalthis'},
    {key: 'm1', value: 'Mistborn I', text: 'Mistborn I'},
    {key: 'm2', value: 'Mistborn II', text: 'Mistborn II'},
    {key: 'm3', value: 'Mistborn III', text: 'Mistborn III'},
    {key: 'st1', value: 'Stormlight I', text: 'Stormlight I'},
    {key: 'st2', value: 'Stormlight II', text: 'Stormlight II'},
    {key: 'st3', value: 'Stormlight III', text: 'Stormlight III'},
    {key: 'wb', value: 'Warbreaker', text: 'Warbreaker'},
    {key: 'alo', value: 'Allomancy', text: 'Allomancy'},
    {key: 'bb', value: 'Biochromatic Breath', text: 'Biochromatic Breath'},
    {key: 'sur', value: 'Surgebinding', text: 'Surgebinding'},
    {key: 'mis', value: 'Mistborn', text: 'Mistborn'},
    {key: 'st', value: 'Stormlight Archive', text: 'Stormlight Archive'},
    {key: 'bog', value: 'Breath of Gods', text: 'Breath of Gods'}
]

export {data};